name: "Code layout"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  c_code_layout:
    name: C linter
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install clang-format
        run: sudo apt-get install clang-format
      - name: Clang-format check
        run: clang-format --dry-run --Werror -style=file pgsql/*.c pgsql/*.h lib/*.c lib/*.cpp lib/*.hpp lib/*.h lib/cunit/*.c lib/cunit/*.h
  sql_code_layout:
    name: SQL linter
    runs-on: ubuntu-20.04
    steps:
      - name: Install nvm
        uses: actions/setup-node@v1
        with:
          node-version: '8'
      - name: Linter
        run: |
          npm install -g eclint@1.1.5
          eclint check * */* */cunit/*
